# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/alons/Desktop/puc/2022-2/sistemas_digitales/proyecto_grupo9/Proyecto_digitales_grupo9/proyecto_grupo9/proyecto_grupo9.srcs/sources_1/ip/Data_Memory/Data_Memory.xci
# IP: The module: 'Data_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alons/Desktop/puc/2022-2/sistemas_digitales/proyecto_grupo9/Proyecto_digitales_grupo9/proyecto_grupo9/proyecto_grupo9.gen/sources_1/ip/Data_Memory/Data_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/alons/Desktop/puc/2022-2/sistemas_digitales/proyecto_grupo9/Proyecto_digitales_grupo9/proyecto_grupo9/proyecto_grupo9.srcs/sources_1/ip/Data_Memory/Data_Memory.xci
# IP: The module: 'Data_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alons/Desktop/puc/2022-2/sistemas_digitales/proyecto_grupo9/Proyecto_digitales_grupo9/proyecto_grupo9/proyecto_grupo9.gen/sources_1/ip/Data_Memory/Data_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
